redboltz/mqtt_cpp

- include/mqtt/client.hpp
RHS of the assignment.
This bug should be detected as an unused parameter warning, but client
is a class template and set_password is not used, so set_password()
isn't instantiated.
I added a test that is using set_password, but test.mosquito.org
rejected the connection that contains password. So I don't add test.
> Replaced the member variable password_ with the parameter password on

- include/mqtt/endpoint.hpp
- test/resend.cpp
Added manual response functionality.
When automatic response mode, puback is sent after publish handler
is finished on QoS1, pubrec is sent after publish handler is finished on QoS2,
pubrel is sent after pubrec handler is finished on QoS2, and pubcomp is
send after pubrel handler is finished on QoS2.
When manual response mode, you need to send puback, pubrec, pubrel, and
pubcomp in the correspoinding hander.
> Fixed puback and pubrel sending timing.

- include/mqtt/endpoint.hpp
- test/resend.cpp
When you set auto_pub_response, even if connection is disconnected
in pubrec handler, pubrel is store for the next connection.
> Fixed pubrel resend.

- include/mqtt/endpoint.hpp
The client's publish handler used to be called when pubrel is received.
I thought that it was the best way to avoid duplicate publish.
However, I found better way.
I introduced the `std::set<std::uint16_t>` that stores packet_id.
The member variable name is qos2_publish_handled_.
When publish is received, check qos2_publish_handled_.
If packet_id has already been stored, client's publish handler is not
called, but pubrec is sent to the client.
If packet_id is not stored, call the client's publish handler and
stores packet_id into qos2_publish_handled_.
When pubrel is received, the packet_id in qos2_publish_handled_ is
removed.
> Changed QoS2 publish handling polcy simpler.

- example/no_tls.cpp
- example/tls.cpp
- include/mqtt/client.hpp
- include/mqtt/endpoint.hpp
- test/connect.cpp
- test/manual_publish.cpp
- test/multi_sub.cpp
- test/pubsub.cpp
- test/pubsub_no_strand.cpp
- test/remaining_length.cpp
- test/resend.cpp
- test/retain.cpp
- test/test_settings.hpp
- test/will.cpp
endpoint and client is now not movable. Use shared_ptr.
make_* functions return shared_ptr.
Fixed #51.
> Fixed incomplete move semantics support.

- include/mqtt/endpoint.hpp
When we close SSL connection on boost::asio libraries, we get "ssl sort read error".
In normally, we get errors and call handle_error(), but we have to close connection in this case.
So I add the code which ignores "ssl short read error" when closes SSL connection.
This problem was reported to Boost Trac.
[Boost C++ Libraries] #12528: boost::asio::ssl_stream "short read error" when a connection is closed
https://svn.boost.org/trac/boost/ticket/12528
> workaround ssl short read error

- include/mqtt/endpoint.hpp
- test/CMakeLists.txt
- test/offline.cpp
You can call publish_* and async_publish_* function family offline.
If clean session == false, and qos is at_least_once or exactly_once,
the published packet will send just after the next connection is established.
> Added offline publish support.

- include/mqtt/endpoint.hpp
When endpoint calls socket.shutdown() , it can be blocked forever (very rare case). It happened my project using mqtt_client_cpp.
I considered replacing shutdown with async_shutdown and set a deadline_timer. But it is a little complicated. 
Simpler solution is just close TCP layer socket. The counter part of the connection could observe TLS_SHORT_READ but it is not a big problem. As far as I used Boost.Asio, SSL_SHORT_READ is unavoidable ( not caused by this modification).
So mqtt_client_cpp treats the SSL_SHORT_READ as a normal close.
> Removed TLS manual shutdown() call.

- include/mqtt/client.hpp
boost::asio's ssl context provides a convenience method `set_default_verify_paths` (see http://www.boost.org/doc/libs/1_64_0/doc/html/boost_asio/reference/ssl__context/set_default_verify_paths.html). Exposing the method from mqtt::client makes it easy for users to select the "right" location to load certificate authorities from.
> Expose set_default_verify_paths for SSL context

- include/mqtt/tcp_endpoint.hpp
- include/mqtt/ws_endpoint.hpp
The readme states the only used C++14 feature are binary literals, so
let's keep it like that if trivially possible like in this case.
Also remove tcp_endpoint::next_layer() method, as the underlying
boost::asio::ip::tcp::socket type doesn't have any such method. (NB: If
this method were actually used in the code, compilation would have
failed before)
> Remove usage of C++14 feature 'return type deduction'.

- include/mqtt/client.hpp
- test/async_pubsub.cpp
- test/connect.cpp
- test/multi_sub.cpp
- test/offline.cpp
- test/pubsub.cpp
- test/pubsub_no_strand.cpp
- test/resend.cpp
- test/retain.cpp
- test/will.cpp
You can set your verify mode and callback. They are passed to asio.
The default verify mode is verify_peer. It is the same as original
behavior.
> Improved TLS verify settings.

- example/no_tls_ws_client.cpp
- include/mqtt/client.hpp
Removed unused capture in example.
> Clean up private functions.

- include/mqtt/endpoint.hpp
- test/connect.cpp
Breaking change.
close_handler will be called only when `disconnect()` or
`async_disconnect()` is called.
If the socket is closed cleanly from server side other reasons, error_handler is
called. Before this fix, close_handler is called.
User usually want to re-connect only when unexpected close is detected.
In other words, user don't want to re-connect in close_handler if the
handler is called by `disconnect()` or `async_disconnect()`.
After the fix, user can achieve the expected behavior writing re-connect
code only in error_handler.
> Fixed #112.

- include/mqtt/client.hpp
- include/mqtt/endpoint.hpp
- test/connect.cpp
It used to be sent each ping_duration_ms_.
After this update, pingreq is sent ping_duration_ms_ passed
after any mqtt control packet sent.
> Improved pingreq sending timing.

- include/mqtt/endpoint.hpp
- test/CMakeLists.txt
- test/length_check.cpp
If the handler returns true, allocate payload memory and continues
receive process, otherwise cancel receive process and call error handler.
> Added length check handler.

- .travis.yml
travis-ci force quit build because the build time over 50min
Addess sanitizer checking is covered by linux build.
> Removed address sanitizer flag from osx build.

- CMakeLists.txt
I got an error while compiling your library for the first time. My machine did not have Boost libraries >= 1.59 installed.
The cmake command generated the Makefile, but after that, the compiler complained about missing boost headers. 
Adding the REQUIRED argument to the FIND_PACKAGE(Boost) command should fix this issue.
> Add the REQUIRED argument to the FIND_PACKAGE(Boost) command

- include/mqtt/endpoint.hpp
The main point of the fix is `async_send_publish()`.
In `do_async_write()` the actual writing prosess is post. And the posted
process could be handled by other thread. Then pubrec, pubrel, and
pubcomp process could be processed **before** `store_.emplace()` is
called.
This fix avoid it. After the fix, `store_.emplace()` is processed **brefore** `do_async_write()`.
> Fixed #158.

- include/CMakeLists.txt
This is the bare minimum that I needed to do in order to use mqtt_cpp with my code.
I have a project structure like this
/
- 3rdparty/mqtt_cpp
- src/CMakeLists.txt
Where my CMakeLists.txt has "add_subdirectory(../3rdparty/mqtt_cpp)", and then I use mqtt_cpp using "target_link_library(myapp mqtt_cpp_iface)"
The pull request does not replace https://github.com/redboltz/mqtt_cpp/pull/149 . There are other good improvements in that other PR.
> Fix include/CMakeLists.txt

- CMakeLists.txt
I'm compiling for a platform where I don't have these other components available.
> Only require boost system when not building unit tests

- CMakeLists.txt
Allow the end user to specify whether to use static boost or not.
Honestly, I would prefer that we just drop this configuration option entirely, as I can set it in my own cmake file that includes the mqtt_cpp one, but it seemed like you wanted this to be default off.
> Choose static boost at configure time

- include/mqtt/endpoint.hpp
- include/mqtt/message.hpp
- include/mqtt/message_variant.hpp
Send multiple messages in `queue_` all at once.
Size limit is not implemented yet.
> Implemented #194.

- CMakeLists.txt
- include/mqtt/any.hpp
- include/mqtt/endpoint.hpp
> Add mqtt::any, based on either std::any or boost::any, replaces life_keeper_t with it

- include/mqtt/endpoint.hpp
- test/pubsub.cpp
- test/sub.cpp
Trying to improve the lifetime management of string objects. Use string_view where ownership doesn't need to transfer, using std::move() where it does.
> Cleanup of various functions regarding strings

- include/mqtt/server.hpp
Added missing `acceptor_.reset()`.
> Added exception handling code.

- include/mqtt/property.hpp
- include/mqtt_client_cpp.hpp
- include/mqtt_server_cpp.hpp
- test/async_pubsub_2.cpp
- test/connect.cpp
- test/pubsub.cpp
- test/resend.cpp
- test/resend_serialize.cpp
- test/resend_serialize_ptr_size.cpp
- test/retain.cpp
- test/sub.cpp
- test/will.cpp
Users needed to set *_ref property types if the property has _ref
type. It was annoying.
Now, user can always use `::recv` type. It's simpler.
> Refined visitor for properties.

- include/mqtt/property.hpp
- test/property.cpp
-- Use the explicit keyword to prevent accidental construction of datatypes that require allocation
-- Take as constructor parameters the data types stored inside the property, allowing to std::move
-- Move several static assertions into the code itself, instead of unit tests, to ensure the assertions are always compiled.
> v5 property allocation management, and static asserts

- include/mqtt/endpoint.hpp
The original purpose of the removed code was if user returns false from
handler, then inform user the next read is stopped.
However, this code passed not only th user hander return false, but also
internal error happens. In the internal error case, `func` is called
twice.
So I removed the code. The user that returns false at the handler, user
alread knows the next read never happen.
> Removed redundant callback.

- test/checker.hpp
Thrown exception in test case are caught by Boost.Test correctly.
> Fixed #314.

- include/mqtt/variant.hpp
Evaluate BOOST_MPL_LIMIT_LIST_SIZE only if
BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS is defined,
otherwise undef BOOST_MPL_LIMIT_LIST_SIZE and redefine
BOOST_MPL_LIMIT_LIST_SIZE to 40.
> Fixed #316.

- test/underlying_timeout.cpp
Due to make timeout situation, the test directly calls beast APIs.
> Fixed lowest_layer call on Boost 1.70.0 or later.

- CHANGELOG.md
- README.md
- include/mqtt/endpoint.hpp
- test/sub.cpp
It didn't work with MQTT v5 subscribe option.
> Fixed invalid qos comparison on subscribe.

- include/mqtt/endpoint.hpp
- include/mqtt/subscribe_options.hpp
Also resolves an accidental change to the parameters for some unsuback functions.
> Add inline keyword to several functions to avoid ODR issue

- include/mqtt/endpoint.hpp
This causes programs that unsubscribe from a topic pattern to stop reading from their socket if they do not have a custom unsuback handler.
This PR fixes the problem for me.
> Ensure that processing unsuback resumes async reading

- include/mqtt/const_buffer_util.hpp
mqtt_cpp requires Boost 1.66.0 or later, so `#if` isn't required any more.
> Fixed BOOST_VERSION typo.

- include/mqtt/async_client.hpp
- include/mqtt/attributes.hpp
- include/mqtt/callable_overlay.hpp
- include/mqtt/client.hpp
- include/mqtt/endpoint.hpp
- include/mqtt/exception.hpp
- include/mqtt/server.hpp
- include/mqtt/sync_client.hpp
- test/test_broker.hpp
- test/test_server_no_tls.hpp
An optional template wrapper, callable_overlay, is provided that provides a collection of std::functions that can
be set to register dynamically changable callbacks for each of the virtual member function calls that can happen.
> Use virtual functions for notifications from mqtt_cpp::endpoint to other code, instead of multiple std::functions

- example/tls_both.cpp
- example/tls_client.cpp
- example/tls_ws_both.cpp
- example/tls_ws_client.cpp
- include/mqtt/client.hpp
- include/mqtt/deprecated_msg.hpp
- include/mqtt/server.hpp
- test/combi_test.hpp
Added get_context().
Marked as deperecated wrapper functions for asio::ssl::context.
> Implemented #471.

- include/mqtt/deprecated.hpp
- test/test_settings.hpp
Renamed from MQTT_DEPRECATED_TEST to MQTT_USE_DEPRECATED.
The macro is documented at https://github.com/redboltz/mqtt_cpp/wiki/Config
> Implemented #499.

- example/v5_no_tls_both.cpp
- example/v5_no_tls_client.cpp
- example/v5_no_tls_prop.cpp
- example/v5_no_tls_server.cpp
- include/mqtt/callable_overlay.hpp
- include/mqtt/client.hpp
- include/mqtt/deprecated_msg.hpp
- include/mqtt/endpoint.hpp
- include/mqtt/property_variant.hpp
- include/mqtt/v5_message.hpp
- include/mqtt/will.hpp
- test/as_buffer_async_pubsub_1.cpp
- test/as_buffer_async_pubsub_2.cpp
- test/as_buffer_pubsub.cpp
- test/as_buffer_sub.cpp
- test/async_pubsub_1.cpp
- test/async_pubsub_2.cpp
- test/connect.cpp
- test/manual_publish.cpp
- test/offline.cpp
- test/pubsub.cpp
- test/resend.cpp
- test/resend_serialize.cpp
- test/resend_serialize_ptr_size.cpp
- test/retain.cpp
- test/sub.cpp
- test/test_broker.hpp
- test/test_util.hpp
- test/will.cpp
This is purely a cosmetic change.
It just replaces the longer name, with the name of the typedef, in the whole codebase.
The goal is to make functions a bit easier to read by using the shorter name.
> Rename std::vector<MQTT_NS::v5::property_variant> as MQTT_NS::v5::properties

- include/mqtt/endpoint.hpp
- include/mqtt/tcp_endpoint.hpp
- include/mqtt/type_erased_socket.hpp
- include/mqtt/ws_endpoint.hpp
User can get executor_type as follows:
```cpp
auto exe = c->socket()->get_executor();
```
And user can use it as
```cpp
boost::deadline_timer tim(exe);
```
> Fixed #526.

- CHANGELOG.md
- README.md
- include/mqtt/endpoint.hpp
Fixed packet_id leak on QoS2 publish.
> Fixed #540.

- include/mqtt/callable_overlay.hpp
- include/mqtt/client.hpp
- include/mqtt/endpoint.hpp
We don't call any of them inside of a try-catch block, so any exceptions thrown would crash the program regardless.
This allows the compiler to make some small optimization assumptions, and more clearly communicates the rules to the end-user of the API.
> Mark virtual functions as noexcept

- include/mqtt/endpoint.hpp
The workaround is enabled only if MQTT_STD_ANY is defined.
> Added std::tuple<std::any> workaround guard.

- include/mqtt/v5_message.hpp
`0U` is `unsigned int`, which is different from (and sometimes smaller than) `size_t`.
This can cause compiler warnings due to potential data loss.
It looks like https://github.com/redboltz/mqtt_cpp/blob/7b7e9090bde8b276175fec3156433b68d8f8ccbb/include/mqtt/v5_message.hpp#L133-L134 may have been an attempt to partially fix the same issue, but it didn't go far enough.
> Fix `accumulate` type

- include/mqtt/publish.hpp
We chose `retain` instead of `publish_retain` but
`publish_retain_to_str()` was remaind.
Fixed copy-past mistake on "invalid_dup".
> Fixed publish options.

- include/mqtt/callable_overlay.hpp
- include/mqtt/client.hpp
- include/mqtt/endpoint.hpp
- include/mqtt/server.hpp
`callable_overlay` always calls the base of `on_pre_send()`,
`on_close()`, and `on_error()`.
It makes sure `client` process is correctly done.
NOTE:
`callable_overlay` is not only used from `client` but also
`endpoint`. That means `endpoint::on_pre_send()` (and other
functions) are called. So I update them from pure virtual function to
non-pure virtual function that has empty definition.
NOTE:
`callable_overlay` calles `base::on_mqtt_processed()` only if
mqtt_processed handler is not set. It is inconsitent behavior to
`on_pre_send()` (and other functions). But it is correct behavior. So
I add documentation about that.
I personally believe this inconsitency doesn't cause a big
problem. Because this handler is for very advanced users. (I use it)
> Fixed #573.

- include/mqtt/endpoint.hpp
- test/resend_serialize_ptr_size.cpp
The message body has packet_id. It is used to use but currently not used.
> Removed packet_id from restoring functions.

- example/redirect.cpp
- example/v5_no_tls_prop.cpp
- include/mqtt/endpoint.hpp
- include/mqtt/message_variant.hpp
- include/mqtt/property_variant.hpp
- include/mqtt/visitor_util.hpp
- test/async_pubsub_2.cpp
- test/connect.cpp
- test/pubsub.cpp
- test/resend.cpp
- test/resend_new_client.cpp
- test/resend_serialize.cpp
- test/resend_serialize_ptr_size.cpp
- test/retain.cpp
- test/sub.cpp
- test/test_broker.hpp
- test/will.cpp
It works well with non const operator()().
It requires boost 1.67 or later.
> Removed boost::static_visitor inheritance.

- include/mqtt/v5_message.hpp
Updated v5_message.hpp to reflect correct flags (0b0010) for reserved bits in pubrel fixed header
> Updated v5_message.hpp pubrel fixed header flags

- include/mqtt/endpoint.hpp
Skip properties phase if remaining length is 0. This is already done at packet id phase, but was missing at reason code. So this addresses the issue in case a puback/pubrec/pubrel/pubcomp received with a reason code (e.g. no matching subscriber), but without a property.
> Skip properties phase if remaining length is 0

- include/mqtt/message.hpp
- include/mqtt/v5_message.hpp
These two messages could appear at for_each_store.
Added member functions are convenient for users.
> Added getters for publish and pubrel message.

- include/mqtt/endpoint.hpp
Thanks to clang 10.0.0, the mismatch is detected.
> Fixed type mismatch warning.

- .github/workflows/gha.yml
This adds:
Link What You Use, a CMake plugin that tells you if you are linking dependencies unnecessarily.
Include What You Use: A tool that will provide guidance on reducing header bloat
Clang-Tidy: A tool that provides suggestions on code with known-bad anti-patterns
Clang-Analyzer: A tool that does in-depth analysis of code to find bugs at compile time.
> Ci analyzer

- include/mqtt/client.hpp
Some applications might want to access the client id on an mqtt_client after it is set. This PR exposes the client id.
> add getter for client_id_

- include/mqtt/client.hpp
- include/mqtt/endpoint.hpp
- include/mqtt/server.hpp
- test/connect.cpp
- test/test_broker.hpp
Added PINGRESP timeout.
If the timeout value is set, when PINGREQ is sent but PINGRESP is not
received until the timeout, then force_disconnect() is called from the
client side internally.
> Implemented #648.

- include/mqtt/client.hpp
When user_name_ or password_ is not set, then set empty optional as the arugmnent.
> Fixed #653.

- include/mqtt/connect_return_code.hpp
- include/mqtt/control_packet_type.hpp
- include/mqtt/publish.hpp
- include/mqtt/reason_code.hpp
- include/mqtt/subscribe_options.hpp
> Replaced template Stream with std::ostream.

- include/mqtt/endpoint.hpp
- test/length_check.cpp
- test/test_broker.hpp
Invalid length on MQTT protocol was `boost::system::errc::message_size`.
But it was not appropriate.
See
https://github.com/redboltz/mqtt_cpp/issues/650#issuecomment-664717365
These errors are replaced with `boost::system::errc::protocol_error`
because it is MQTT protocol violation.
Unexpected boost asio transferred_size error was also mapped
`boost::system::errc::message_size`.
It is replaced with `boost::system::errc::bad_message`.
> Fixed error code.

- include/mqtt/client.hpp
- include/mqtt/constant.hpp
- include/mqtt/endpoint.hpp
- include/mqtt/setup_log.hpp
- include/mqtt/topic_alias_recv.hpp
- include/mqtt/type.hpp
- test/CMakeLists.txt
- test/as_buffer_async_pubsub_1.cpp
- test/as_buffer_async_pubsub_2.cpp
- test/as_buffer_pubsub.cpp
- test/as_buffer_sub.cpp
- test/async_pubsub_1.cpp
- test/async_pubsub_2.cpp
- test/connect.cpp
- test/length_check.cpp
- test/manual_publish.cpp
- test/multi_sub.cpp
- test/pubsub.cpp
- test/pubsub_no_strand.cpp
- test/remaining_length.cpp
- test/resend.cpp
- test/retain_1.cpp
- test/retain_2.cpp
- test/sub.cpp
- test/test_broker.hpp
- test/topic_alias_recv.cpp
TopicAlias lifetime is the same as Session lifetime
It is different from MQTT v5 spec but practical choice.
See
https://lists.oasis-open.org/archives/mqtt-comment/202009/msg00000.html
Related fix:
When topic is empty and no topic alias entry is found, then
protocol_error.
The broker send DISCONNECT packet with protocol_error reason code.
process_disconnect implementation was simply doesn't call
`on_mqtt_message_processed()` but it was bad.
It caused exit from ioc.run() loop because the next async_read was not
called.
The correct behavior is calling `on_mqtt_message_processed()` and close
socket. The endpoint can detect the socket close by on_error().
> Added topic alias support.

- include/mqtt/endpoint.hpp
- test/connect.cpp
> Fixed topic_alias_recv test failure.

- include/mqtt/log.hpp
- include/mqtt/setup_log.hpp
It is mandatory for macros because macro simply replace string.
> Added explicit namespace qualification.

- include/mqtt/type_erased_socket.hpp
Fixed compile error on boost 1.74.0 or later.
If boost version is lower than 1.74.0 or
BOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT is defined, then use
boost::asio::executor, otherwise use boost::asio::any_io_executor on
type erased socket.
> Fixed #669.

- include/mqtt/log.hpp
- include/mqtt/setup_log.hpp
- test/global_fixture.hpp
- test/pubsub_no_strand.cpp
- test/test_broker.hpp
online and offline subscribers has common member function `deliver`.
It is a preparation for cross collection roundrobin iteration for shared
subscriptions in the future.
Apply coding rules.
Renamed types and variables.
Refined logs.
> Refined online and offline sessions and subscribers.

- test/test_broker.hpp
It seems that #672 contains not only shared subscription
support (incomplete) but also wildcard bug fix.
This is the part of wildcard bug fix.
> Fixed wildcard bugs.

- .github/workflows/gha.yml
- include/mqtt/string_view.hpp
- test/CMakeLists.txt
- test/subscription_map.cpp
- test/subscription_map_broker.cpp
- test/topic_filter_tokenizer.hpp
The tests forcused on using it on the broker.
> Added subscription_map tests.

- include/mqtt/string_view.hpp
- test/retained_topic_map.cpp
- test/retained_topic_map.hpp
- test/subscription_map.hpp
PR is ready now, compile fix was removed. One of the unit tests was deadlocking, the timeout on the CI for the test is too large.
> Use multiindex in retained_map to use both hash map as well as ordered index

- test/subscription_map.cpp
- test/subscription_map.hpp
- test/subscription_map_broker.cpp
- test/test_broker.hpp
Allow modification of matched topicsI changed the underlying storage of multiple_subscription_map from std::set to std::unordered_map. This improves the performance of the insert/delete operation and the map allows for updating a key in the map. The multiple_subscription_map now stores multiple key => value pairs per subscription. Insertion is changed as follows:
```C++
multiple_subscription_map<std::string, int> map; 
map.insert_or_update("a/b/c", "123", 0); // Insert
map.insert_or_update("a/b/c", "123", 1); // Update
map.erase("a/b/c", "123"); // Erase key
````
The find operation now gives the key and value as argument to the callback:
````C++
map.find("a/b/c", [](std::string const &key, int value) {
});
````
A hash and equal_to now needs to be defined for the key that is stored: …
> Converted subscription map from set to hash map

- test/retained_topic_map.cpp
- test/retained_topic_map.hpp
- test/retained_topic_map_broker.cpp
- test/subscription_map.cpp
- test/subscription_map.hpp
- test/subscription_map_broker.cpp
- test/test_broker.hpp
Emplace with piecewise_construct is used now to perform insert_or_update. Also retained map performed a move on const reference. This was also not good.
> Subscription map and retained map allow storing move-only classes

- example/no_tls_both.cpp
The port of the server already gets stored inside a local variable, so we should use this one instead of doing another lexical cast at server creation
> simplify server creation

- include/mqtt/endpoint.hpp
- include/mqtt/message.hpp
- include/mqtt/v5_message.hpp
- test/async_pubsub_2.cpp
- test/message.cpp
- test/pubsub_1.cpp
Single boost::asio::const_buffer payload is originally supported.
This PR added scattered payload publish.
It is very useful for request - modify - response ( or forward ) pattern.
> Supported ConstBufferSequence payload publish.

- example/redirect.cpp
- include/mqtt/callable_overlay.hpp
- include/mqtt/endpoint.hpp
- include/mqtt/message_variant.hpp
- include/mqtt/property_variant.hpp
- test/resend.cpp
- test/resend_new_client.cpp
- test/test_broker.hpp
- test/topic_alias_recv.cpp
Fixed for_each_store and restore_serialized_message parameter type.
It should be basic_store_message_variant but it was
basic_message_variant.
basic_store_message_variant could have publish and pubrel.
It is appropriate for storing inflight messages.
> Added broker-side inflight message resend support.

- test/broker_offline_message.cpp
- test/combi_test.hpp
- test/retain_2.cpp
- test/retained_topic_map.hpp
- test/test_broker.hpp
- test/will.cpp
This is what I have so far:
Retained message expiry (tested)
Will expiry (tested)
Offline message expiry (no test)
The message expiry is updated when the message is finally transmitted, this is also untested yet.
The unit tests for this are a bit of a hassle, is it maybe better to use synchronous clients, much easier to write the test. Also, when the unit test stalls, there is no real timeout on the unit test. That is also why the CI hangs sometimes.
> Implement message expiry in broker

- .github/workflows/gha.yml
- azure-pipelines.yml
- include/mqtt/endpoint.hpp
- include/mqtt/log.hpp
- include/mqtt/topic_alias_recv.hpp
- include/mqtt/v5_message.hpp
- test/CMakeLists.txt
- test/args_provider.ps1
- test/args_provider.sh
- test/broker_offline_message.cpp
- test/resend.cpp
- test/retain_2.cpp
- test/retained_topic_map.cpp
- test/subscription_map.hpp
- test/test_broker.hpp
- test/will.cpp
Fixed message expiry interval is 0 case.
The interval 0 is different from absent of the interval.
The absent interval means no expiration.
There is no specific notation about interval 0.
That means regard the interval 0 as 0 second.
So the timer will fire immediately.
I have another design option. If the interval is 0 then skip
sending/storing process. But I don't choose it. It requires additional
logic.
boost asio steady_timer accept 0 timer. So I use the same logic as the
intarval has seconds value.
NOTE:
session expiry interval is different. Absent means explicit set 0.
> Added message expiry interval support for inflight messages.

- include/mqtt/endpoint.hpp
- test/system/CMakeLists.txt
- test/system/st_broker.cpp
- test/system/st_issue_749.cpp
It is for test. st_broker is unfinished. It is expected.
> System test broker with crash

- .github/workflows/gha.yml
- include/mqtt/endpoint.hpp
- test/system/st_async_pubsub_2.cpp
- test/system/st_pubsub_1.cpp
Invalid client may send pubrec twice with the same packet_id.
Then the broker send pubrel twice and the second one causes assertion
fail.
But assertion fail is for logic error. It is actually happened by the
invalid client.
So, just overwrite pubrel message to the store. No assertion fail.
> Fixed invalid assertion fail on (sync) pubrel sending.

- include/mqtt/broker/broker.hpp
The broker sent CONNACK even if MQTT connection hadn't been established.
It caused assertion failed.
In this case, the broker should simply close connection.
> Fixed #768.

- include/mqtt/endpoint.hpp
- include/mqtt/packet_id_manager.hpp
- include/mqtt/value_allocator.hpp
- test/unit/CMakeLists.txt
- test/unit/ut_packet_id.cpp
- test/unit/ut_value_allocator.cpp
1. Added generic value_allocator class template. It is more efficient
that the original implementation.
2. Moved packet_id management code to the separated file
`packet_id_manager.hpp` that uses value_allocator.
3. Removed retun value of release_packet_id() to support efficient implementation.
NOTE:
The packet_id allocation algorithm has been changed.
The smallest value that is vacant is always allocated.
> Improved packet_id allocation.

- include/mqtt/broker/broker.hpp
- include/mqtt/broker/inflight_message.hpp
- include/mqtt/broker/session_state.hpp
- include/mqtt/broker/shared_target.hpp
- include/mqtt/endpoint.hpp
- include/mqtt/property.hpp
- include/mqtt/property_variant.hpp
- include/mqtt/time_point_t.hpp
- include/mqtt/topic_alias_recv.hpp
- include/mqtt/topic_alias_send.hpp
- include/mqtt/v5_message.hpp
- include/mqtt/value_allocator.hpp
- test/system/CMakeLists.txt
- test/system/st_topic_alias.cpp
- test/unit/CMakeLists.txt
- test/unit/ut_topic_alias.cpp
The the TopicAlias map should be cleared on disconnection.
If the inflight message has the TopicAlias property, remove it.
If the inflight message has the empty TopicName and the TopicAlias,
the original TopicName is recovered from the TopicAlias at the first
sent, and remove TopicAlias property.
It works well with mosquitto MQTT broker.
The original mqtt_cpp implementation cause protocol error because of
using cleared topic alias on resend.
> Fixed TopicAlias functionality.

- include/mqtt/endpoint.hpp
- include/mqtt/packet_id_type.hpp
- include/mqtt/two_or_four_byte_util.hpp
Applied boost asio's stackless coroutine to `process_mqttpacket` functions.
I expected faster compile time but no significant difference observed.
maset 0a0c6a9bd4ec0d324a0c1314e23e921f48743f17
```
Command being timed: "make no_tls_both"
User time (seconds): 37.66
System time (seconds): 1.81
Percent of CPU this job got: 99%
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:39.54
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): 2980752
Average resident set size (kbytes): 0
Major (requiring I/O) page faults: 0
Minor (reclaiming a frame) page faults: 1013237
Voluntary context switches: 62
Involuntary context switches: 676
Swaps: 0
File system inputs: 0
File system …
```
> Apply asio stackless coroutine.

- include/mqtt/broker/broker.hpp
- include/mqtt/endpoint.hpp
- include/mqtt/topic_alias_recv.hpp
- include/mqtt/topic_alias_send.hpp
- test/system/st_topic_alias.cpp
It used to be fixed as 0xffff.
Now, we can set it using set_topic_alias_maximum() member function.
The client also set it by connect()/async_connect() with property topic_alias_maximum.
> Added topic alias maximum for receiving functionality.

- include/mqtt/async_client.hpp
- include/mqtt/endpoint.hpp
- test/system/st_resend.cpp
qos2_publish_handled_ was inserted and erased but not referenced.
When PUBLISH QoS2 packet is received, if qos2_publish_handled_ has the
packet_id then on_publish isn't called. (Exactly once delivery)
See #49.
> Fixed qos2_publish_handled_ logic.

- example/broker.cpp
- example/tls_both.cpp
- example/tls_both_client_cert.cpp
- example/tls_server.cpp
- example/tls_ws_both.cpp
- example/tls_ws_server.cpp
- test/system/test_ctx_init.hpp
Replaced use_certificate_file with use_certificate_chain_file.
If certificate file contians one certification, both ok.
However, if the certificate file contains intermidiate certificate and
server certificate, then only use_certificate_chain_file works.
See
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_use_certificate.html
> Updated certificate function call.

- include/mqtt/broker/broker.hpp
- test/system/st_connect.cpp
- test/system/st_topic_alias.cpp
- test/unit/ut_property.cpp
Removed invalid maximum_qos (exactly_once) property.
It should be absent if exactly_once.
Only at_most_once (0), or at_least_once (1) is allowed.
> Fixed #843.

- include/mqtt/broker/broker.hpp
- include/mqtt/broker/broker_config.hpp
- test/system/st_connect.cpp
MQTT requires to send DISCONNECT with reason code and then close the
connection from the broker side but Windows requires some delay.
> Added workaround code for windows.

- test/system/combi_test.hpp
- test/system/st_as_buffer_async_pubsub_1.cpp
- test/system/st_as_buffer_async_pubsub_2.cpp
- test/system/st_as_buffer_pubsub.cpp
- test/system/st_as_buffer_sub.cpp
- test/system/st_async_pubsub_1.cpp
- test/system/st_async_pubsub_2.cpp
- test/system/st_connect.cpp
- test/system/st_length_check.cpp
- test/system/st_manual_publish.cpp
- test/system/st_maximum_packet_size.cpp
- test/system/st_multi_sub.cpp
- test/system/st_offline.cpp
- test/system/st_pubsub_1.cpp
- test/system/st_pubsub_2.cpp
- test/system/st_receive_maximum.cpp
- test/system/st_remaining_length.cpp
- test/system/st_resend.cpp
- test/system/st_retain_1.cpp
- test/system/st_retain_2.cpp
- test/system/st_sub.cpp
- test/system/st_topic_alias.cpp
- test/system/st_utf8string_validate.cpp
Added session_taken_over tests for all combination (TLS/WS).
> Supported combi test with multi clients.

- CHANGELOG.md
- README.md
- include/mqtt/async_client.hpp
- include/mqtt/broker/broker.hpp
- include/mqtt/client.hpp
- include/mqtt/endpoint.hpp
- include/mqtt/sync_client.hpp
- Renamed client's async_store_send to async_operation.
Now it is not only for sending stored messages but also for all automatic messages.
- Removed set_auto_pub_response()'s 2nd parameter.
- Removed set_async_notify() for DISCONNECT/CONNACK.
- Removed set_async_pingreq().
- Added set_async_operation(). for all automatic operations.
> Unified async/sync selector for automatic operation.

- CMakeLists.txt
- example/CMakeLists.txt
boost::program_options cmake requirement moved to example directory.
> Fixed #858.

- CHANGELOG.md
- example/broker.conf
- example/broker.cpp
- include/mqtt/broker/broker.hpp
- include/mqtt/broker/offline_message.hpp
- include/mqtt/broker/session_state.hpp
- include/mqtt/server.hpp
The original design was calling `ioc.run()` from multple threads.
It worked well but scale out limit is up to about 8 threads.
The pps is 120,000 publish / second (QoS0). It was pretty nice but only
8 cores ware used.
I tested it on AWS 48 vcpu environment.
When I used 48 threads, the result was the same as 8 threads.
I suspected OS or VM limit. But when I ran the two broker processes that
listens different port, then each broker resulted 120,000 pps.
So total is 240,000 pps.
It indicates the limit is not caused by OS or VM.
Finally, I found the bottle neck. It is io_context.
So I updated as follows:
1. Separated io_contexts.
For timer, for accepting connections, and for MQTT communication.
For MQTT communication, I prepared io_context as the same number of
the threads.
2. Added server …
> Assign io_context for each thread.

- include/mqtt/broker/broker.hpp
- test/system/st_connect.cpp
Fixed connack() sending code. It should be async_connack().
> Added no CONNACK response broker emulation.

- CHANGELOG.md
- example/broker.conf
- example/broker.cpp
Set 0 (automatic) is default value of broker.conf
> Fixed automatic threads_per_ioc logic.

- include/mqtt/broker/broker.hpp
- include/mqtt/broker/session_state.hpp
endpoint has qos2 duplicated transfer avoiding mechanism.
It is implemented by `qos2_publish_handled_`.
endpoint works for both client and broker.
However broker (server) is different from the client.
Client can reconnect usign the same endpoint instance as the previous
connection. But the broker can't.
It is because accepting mechanism. On accept, the server needs to create
the new endpoint.
So the broker had an original qos2 duplicated transfer avoiding
mechanism.
It is implemented by `qos2_publish_processed_`.
But the implementation is a little redundant.
So I introduced get and restore functionality for
`qos2_publish_handled_`.
It was #873 but it had bug. `qos2_publish_processed_` was mixed.
This PR completely removed `qos2_publish_processed_` related code from
the broker and added …
> Fixed broker side qos2 exactly once logic.

- include/mqtt/client.hpp
In order to support strand support before connect().
> Added setup_socket() on constructor.

- example/cli.conf
- example/client_cli.cpp
Renamed cacert to verify_file.
Added missing load_verify_file() call.
> Added client certificate options.

- include/mqtt/broker/session_state.hpp
async_force_disconnect() was called twice from the broker side  on
disconnection.
One is broker.hpp, the other is session_state.hpp
The latter isn't needed.
> Removed async_force_disconnect() call from session_state.

- include/mqtt/broker/retained_topic_map.hpp
- include/mqtt/broker/security.hpp
- include/mqtt/broker/topic_filter.hpp
- include/mqtt/endpoint.hpp
- include/mqtt/shared_ptr_array.hpp
- include/mqtt/string_view.hpp
- include/mqtt/v5_message.hpp
* Do not include Boost variations of std::optional and std::any when their respective MQTT_STD_XXX options are set.
* Do not assume that std::string_view can be constructed from a pair of iterators because that is a C++20 feature.
* Correctly check for support for `std::make_shared<T[]>`. See https://en.cppreference.com/w/cpp/feature_test
* Do not use <iostream> in `retained_topic_map.hpp` just to get access to `std::endl`, use `'\n'` instead.
Including headers that are not used unnecessarily increases compile times. It is considered good practice to [include only what you use](https://github.com/include-what-you-use/include-what-you-use).
Enabling the MQTT_STD_XXX options should not assume presence of full C++20 support, otherwise a user's application might not compile even if they are …
> Improve MQTT_STD_XXX behavior

- example/bench.cpp
- example/broker.cpp
- example/client_cli.cpp
- include/mqtt/broker/retained_topic_map.hpp
- include/mqtt/log.hpp
- include/mqtt/setup_log.hpp
Avoid including headers that are only needed when MQTT_USE_LOG is enabled.
Reduce the compile times and avoid unexpected linkage with Boost.Log libraries (e.g. when Boost auto-link is enabled).
I am happy that mqtt_cpp provides such log customization option. I used it to adapt [spdlog](https://github.com/gabime/spdlog). The code for it here as a reference for other users:
mqttCpp.h:
```cpp
#pragma once
#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/comparison/greater_equal.hpp>
#include <boost/preprocessor/if.hpp>
#include <spdlog/common.h>
#include <source_location>
#include <sstream>
#include <string_view>
#define MQTT_NS mqtt_cpp
// forward declare mqtt_cpp severity_level
namespace mqtt_cpp
{
enum class severity_level;
}  // namespace mqtt_cpp
namespace my_app
{ …
```
> Do not include Boost.Log related headers when MQTT_USE_LOG is off

- test/system/st_resend.cpp
CI sometimes failure due to slow execution speed on CI enrivonment.
> Adjusted timing for CI (appveyor),

- include/mqtt/log.hpp
These macros should have guards since we expect users to define them themselves in order to customize logging as demonstrated with spdlog in an earlier pull request: https://github.com/redboltz/mqtt_cpp/pull/927.
> Add define guards to MQTT_LOG macros when MQTT_USE_LOG is off

- include/mqtt/endpoint.hpp
If the 2nd async_shutdown() is called during the 1st async_shutdown processing, then the 2nd async_shutdown() is called immediately. It should be called the 1st handler calling timing.
> Fixed invalid timing async_shutdown handler call.

- include/mqtt/server.hpp
The first problem is the callback function that is set by set_verify_callback() is not called the first accept. But the second accept and later one is called.
I analyzed the problem.
server.hpp calls ctx_.set_verify_callback() int do_accept(). ctx_ is moved from user at the constructor.
Then it is passed to socket_t parameter (actual type is ssl::stream). The type of parameter is `ssl::context&` but it behaves as copy in the constructor. So ctx_ configuration must be finished before socket_t is created.
I updated the order.
Then the first problem is solved.
However, the second problem is appared.
The username that is set by the callback is wrong. This is caused by ctx_.set_verify_callback() overwriting.
The second do_accept() is called when the first TCP async_accept (lowest_layer) is …
> Fixed client certificate treatment.

- include/mqtt/endpoint.hpp
qos2_publish_handled_ is used for avoid qos2 publish handling twice or more. On publish receive, if it doesn't contain the packet_id, then handle the publish message and add the packet_id to qos2_publish_handled_. On pubrel receive, erase the packet_id from qos2_publish_handled_ because the publish packet that has the packet_id is no logner resend. It is the basic logic.
However, when user sends pubrec with error reason_code, then the communication partner doesn't send back pubrel due to the error. In this case, there is no chance to erase qos2_publish_handled_ entry.
It should be erased when user sends pubrec with error reason_code. This fix adds it.
qos2_publish_handled_ used to access from only on strand. But this addition introduce out of strand access. It is user's timing. So I …
> Fixed qos2_publish_handled_ invalidly remains issue.

- include/mqtt/endpoint.hpp
It should be do before publish handler is called.
> Fixed qos2_publish_handled_ insertion timing.
