include/mqtt/client.hpp
test/pubsub.cpp
test/retain.cpp

Unified using packet id and resend buffer as 'store'.
Fixed bad re-deliver problem.

Improved packet_id generating method.

---

include/mqtt/client.hpp
include/mqtt/remaining_length.hpp
test/CMakeLists.txt
test/remaining_length.cpp

Added tests for remaining length.

Fixed a remaining length calculating algorithm.

---

include/mqtt/client.hpp

Current code is dangerous when char is signed.

Added static_cast when creating std::uint16_t from 2 chars.

---

example/no_tls.cpp
example/tls.cpp
include/mqtt/client.hpp
include/mqtt/connect_flags.hpp
include/mqtt/endpoint.hpp
include/mqtt/exception.hpp
include/mqtt/null_strand.hpp
test/CMakeLists.txt
test/connect.cpp
test/manual_publish.cpp
test/multi_sub.cpp
test/pubsub.cpp
test/pubsub_no_strand.cpp
test/remaining_length.cpp
test/resend.cpp
test/retain.cpp
test/test_settings.hpp
test/will.cpp

Supported async write with queuing.
Separated in common features between clients and servers as endpoint.
Added callback handler to inform connection finishing state. That removed exceptions.

Async write

---

.travis.yml
include/mqtt/endpoint.hpp

Limit has been changed from 3bytes to 4bytes.

Fixed remaining length handling logic.

---

README.md

Added boost version requirement to README.md.

---

include/mqtt/endpoint.hpp

publish handler calling timing has been changed.

Changed pubrec auto returning policy.

---

include/mqtt/ws_endpoint.hpp

Added set_option.
Fixed recursive async_read logic.

Updated Beast.

---

include/mqtt/endpoint.hpp

You can call `acquire_unique_packet_id()` or
`register_packet_id(some_id)`, and then call acquired_xxx (e.g. `acquired_publish()`).

Added explicit packet_id operation.

---

include/mqtt/endpoint.hpp

It is not related to acquisition.

Fixed async_suback_imp.

---

include/mqtt/endpoint.hpp
include/mqtt/ws_endpoint.hpp

Fixed shutdown from client. It always close TCP layer.

Fixed websocket close parameter.

---

include/mqtt/connect_flags.hpp
include/mqtt/publish.hpp

These commits fix several warnings while compiling with Visual Studio 2015.

Vs2015 warning fix

---

test/test_broker.hpp
test/will.cpp

Fix will test

---

CHANGELOG.md
README.md

Renamed to `mqtt_cpp` from `mqtt_client_cpp`.

Updated to 1.0.5.

---

example/CMakeLists.txt
example/no_tls_client.cpp
test/CMakeLists.txt
test/async_pubsub.cpp
test/connect.cpp
test/manual_publish.cpp
test/multi_sub.cpp
test/offline.cpp
test/pubsub.cpp
test/pubsub_no_strand.cpp
test/remaining_length.cpp
test/resend.cpp
test/retain.cpp
test/test_main.hpp
test/will.cpp

Test cases are separeted individually.

Refined cmake tree.

---

CMakeLists.txt
include/mqtt/client.hpp

Added conditional include for beast.
Added new resolver interface support.

Supported boost 1.66.0.

---

include/mqtt/endpoint.hpp

Fixed accessibility of member functions. (minimized)

---

include/mqtt/endpoint.hpp

This commit fixes the following problem:
After TCP connection is established, if the client sends connack instead
of connect, then server accepts mqtt connectin. It's invalid.

Fixed malformed connack sending.

---

include/mqtt/endpoint.hpp
include/mqtt/shared_const_buffer_sequence.hpp
test/CMakeLists.txt
test/resend_serialize_ptr_size.cpp
test/test_broker.hpp

Removed copy from test_broker.
Added shared_ptr publish overloads.

Re-design buffer management to avoid payload copy.

---

.travis.yml
example/CMakeLists.txt
test/CMakeLists.txt

Added -Wno-ignored-qualifiers option to suppress boost/beast warnings.
Added CXXFLAGS, CFLAGS, and LDFLAGS on script.
Fixed compiler flags location and order.
Updated clang.
Updated sudo setting.

Improved travis-ci settings.

---

include/mqtt/client.hpp
include/mqtt/endpoint.hpp
test/resend_serialize.cpp
test/resend_serialize_ptr_size.cpp

Added and fixed doxygen comments.

Fixed pubrel serialize.

---

.travis.yml
example/CMakeLists.txt
include/mqtt/utility.hpp
test/CMakeLists.txt

Fixed string_view definition.
Updated travis-ci matrix.

Fixed #145.

---

include/mqtt/server.hpp

Close acceptor if error is occurred.

Supported re-listen.

---

include/mqtt/endpoint.hpp

Added BOOST_ASSERT to store_ insertion to detect inconsistent store_ and  packet_id_.
Added packet_id_ insertion code for starting with pubrel case.

Add store assert

---

include/mqtt/message.hpp

Updated connect message to use packet_id caluclation.

Fixed 32bit packet_id for publish message.

---

test/test_broker.hpp

Fixed #178.

---

test/test_broker.hpp

Please double check that I'm not inadvertently breaking something.

test_broker.hpp / connect_proc -- merge some duplicated logic

---

test/test_broker.hpp

Replaced overwrite approach with pending approach when the client
connecting that has the same client id as existing connection.

Fixed #205.

---

include/mqtt/endpoint.hpp

It is corner case but BOOST_ASSERT is too strong.
Overwrite is better solution.

Replaced BOOST_ASSERT with overwrite.

---

CHANGELOG.md
README.md

Acked-by: Takatoshi Kondo <redboltz@gmail.com>

Updated CHANGELOG and readme.

---

include/mqtt/async_client.hpp
include/mqtt/client.hpp

Added asynchronous pingreq sending mode.
Use asynchronous mode from async_client.

Fixed #266.

---

include/mqtt/property.hpp
test/CMakeLists.txt
test/property.cpp

Added property conversion between non_ref and ref types.

Fixed #279.

---

.travis.yml
CMakeLists.txt
azure-pipelines.yml

Added `MQTT_` prefix to BUILD_TESTS and BUILD_EXAMPLES.

Fixed #269.

---

include/mqtt/four_byte_util.hpp
include/mqtt/message.hpp
include/mqtt/property.hpp
include/mqtt/two_byte_util.hpp
include/mqtt/v5_message.hpp

Removed byte sequence creation macro.

Fixed #280.

---

include/mqtt/property.hpp
test/property.cpp

Added stream output operators for properties.

Fixed #281.

---

include/mqtt/server.hpp
test/CMakeLists.txt
test/underlying_timeout.cpp

Added underlying timeout for servers.

Fixed #295.

---

test/test_server_no_tls.hpp
test/test_server_no_tls_ws.hpp
test/test_server_tls.hpp
test/test_server_tls_ws.hpp

Added reuse_address option to acceptor.

Fixed #305 (possibly)

---

include/mqtt/endpoint.hpp

Added life_keeper to send_pubrel and async_send_pubrel.
Since MQTT v5, pubrel message can have properties.
The properties can contain ref messages.
The messages that can be stored are publish and pubrel.
The publish message already has the same mechanism.
This PR added thae same mechanism for pubrel message.
Other message such as subscribe are not stored.
If it has ref properties and send asynchronously,
simply capture the life keeping object to async_hander.

Fixed #301.

---

include/mqtt/v5_message.hpp

Removed moved `props` accessing code.

Fixed #300.

---

include/mqtt/async_client.hpp
include/mqtt/client.hpp
include/mqtt/endpoint.hpp

Added asynchronous sending stored message on handle_connack()
functionality.
It is switched by `bool async_send_store_` member variable.

Partial fix of #237.

---

include/mqtt/property.hpp

Added store type alias. It is always non ref type.

Fixed #302.

---

include/mqtt/property_parse.hpp
include/mqtt/v5_message.hpp

Fixed invalid-pointer-pair by address sanitizer.

Fixed #321.

---

.travis.yml
include/mqtt/any.hpp

Fixed build error when MQTT_STD_ANY is enabled. #327

Fixed build errors with MQTT_STD_ANY=ON

---

include/mqtt/ws_endpoint.hpp

Supported Boost.1.70.0 or later API change of beast.

Fixed #352.

---

CHANGELOG.md
README.md
include/mqtt/endpoint.hpp
test/async_pubsub_2.cpp

Added missing argument for `async_send_publish()`.
Added tests.
Updated the version to 6.0.1.

Fixed #375.

---

CHANGELOG.md
README.md
include/mqtt/endpoint.hpp

Added props as the default parameter for subscribe/unsubscribe.

Fixed #382.

---

test/underlying_timeout.cpp

Removed WebSocket code from non WebSocket test.

Fixed #389.

---

include/mqtt/endpoint.hpp

See
https://github.com/redboltz/mqtt_cpp/pull/402

Backport #402.

---

.gitmodules
CHANGELOG.md
CMakeLists.txt
README.md

Fixed minimum boost requirement.
Removed beast.

Updated the version to v6.0.5.

---

.travis.yml
CMakeLists.txt
include/CMakeLists.txt
include/mqtt/exception.hpp
include/mqtt/message.hpp

Added check_deps target to check include file.
It is linux only, so far.

Fixed #399.

---

example/v5_no_tls_both.cpp
example/v5_no_tls_prop.cpp
example/v5_no_tls_server.cpp

Fixed #437.

---

include/mqtt/reason_code.hpp

Fixed #449.

---

include/mqtt/client.hpp

Maybe I did something wrong in merging process.

Fixed invalid comment.

---

example/no_tls_both.cpp
example/no_tls_server.cpp
example/no_tls_ws_both.cpp
example/no_tls_ws_server.cpp
example/tls_both.cpp
example/tls_server.cpp
example/tls_ws_both.cpp
example/tls_ws_server.cpp
example/v5_no_tls_both.cpp
example/v5_no_tls_server.cpp
include/mqtt/reason_code.hpp
test/test_broker.hpp

Added qos to suback_[reason|return]_code functions.

Fixed #452.

---

include/mqtt/client.hpp

Added static_assert for TLS support checking.

Fixed #497.

---

include/mqtt/endpoint.hpp

These functions are only internal implementation details, and now that we no longer support variadic functions as part of the user facing API, serve no purpose.

Remove use of variadic template functions

---

.travis.yml

Doesn't trigger branch push.
But master (merged) and release tag trigger travis-ci.

Fixed #520.

---

include/mqtt/buffer.hpp
include/mqtt/shared_ptr_array.hpp

Use const_shared_ptr_array instead of shared_ptr_array.

Fixed #530.

---

.github/workflows/gha.yml

* opened means first creation.
* synchronize means additional push on the exisiting PR.
NOTE: reopened and edited don't affect the code.

Refined CI trigger on pull request.

---

include/mqtt/server.hpp
include/mqtt/ws_endpoint.hpp

* Replaced deprecated async_accept_ex with set_option and async_accept.
* Replaced multi_buffer with flat_buffer.

Updated the client codes for the beast.

---

include/mqtt/tcp_endpoint.hpp
include/mqtt/type_erased_socket.hpp
include/mqtt/ws_endpoint.hpp

Added native_handle() to type erased socket.

Implemented #575.

---

example/CMakeLists.txt
example/redirect.cpp
include/mqtt/endpoint.hpp
include/mqtt/exception.hpp
test/CMakeLists.txt
test/resend_new_client.cpp
test/test_util.hpp

Added redirect example.
Added inheriting store test.
Added variant version of restore_serialized_message().
Refined for_each_store() parameter type.

Added redirect related code.

---

include/mqtt/endpoint.hpp

Fixed message version of for_each_store.

---

include/mqtt/v5_message.hpp

Property Length is appeded only when properties are not empty.

Fixed #601.

---

include/mqtt/client.hpp
test/connect.cpp

A mistake from the last pull request, sorry.

Fix wrong function call

---

.github/workflows/gha.yml

This reverts commit 674443445dc33fc3729efafd0c4e89119bcab9f6, reversing
changes made to 8e9d3e7ecc92ab93500fc8236a0eb2dd1e9a31d5.

Revert "Merge pull request #623 from jonesmz/ci-analyzer"

---

include/mqtt/endpoint.hpp

from a snapshot of the most recent traffic processed, to an accumulator.

Change total_bytes_received_

---

include/mqtt/client.hpp

The goal behind this pull request is to slightly reduce the number of template instantiations.
Compile time and memory use is pretty big for mqtt_cpp, so I'm trying to make some improvements to that.

Simplify the client.hpp connect functions slightly

---

test/retain_2.cpp
test/test_broker.hpp

Added retain handling tests. Fixed invalid assert.
Added retain as published tests.

Added retain tests.

---

test/retained_topic_map.cpp
test/retained_topic_map.hpp

Added erase upper first test on retained_topic_map.

---

test/retained_topic_map.cpp
test/retained_topic_map.hpp
test/subscription_map.cpp
test/subscription_map.hpp

- Calculate size of subscription map and retained map
- Fix for reference counting in retained map

Calculate size of subscription map and retained map,

---

test/test_broker.hpp

Erase not only offline session but also offline sucscriptions.

Fiexed session expire.

---

test/retained_topic_map.hpp
test/subscription_map.cpp
test/subscription_map.hpp

Based on feedback from @jonesmz i created this PR with many updates to the subscription and retained map. Also some invalid iterators were used and fixed in this patch. Some more methods made const, additional error checking, etc ...
@jonesmz I tried using the bitfield with template specialization, but it has drawbacks as well. I made specialization for uint32_t and uint64_t, but macos uses unsigned long, and when I made this specialization, unsigned long was defined as uint64_t at other platforms ...

Many cleanups and improvements to subscription and retained map

---

include/mqtt/buffer.hpp
include/mqtt/callable_overlay.hpp
include/mqtt/client.hpp
include/mqtt/constant.hpp
include/mqtt/endpoint.hpp
include/mqtt/four_byte_util.hpp
include/mqtt/hexdump.hpp
include/mqtt/log.hpp
include/mqtt/message_variant.hpp
include/mqtt/move.hpp
include/mqtt/property.hpp
include/mqtt/property_variant.hpp
include/mqtt/reason_code.hpp
include/mqtt/setup_log.hpp
include/mqtt/subscribe_options.hpp
include/mqtt/topic_alias_recv.hpp
include/mqtt/two_byte_util.hpp
include/mqtt/type.hpp
include/mqtt/v5_message.hpp
include/mqtt/variable_length.hpp
include/mqtt/variant_visit.hpp
include/mqtt/will.hpp

Removed redundant MQTT_NS:: qualification.

Fixed missing namespace.hpp.

---

include/mqtt/ws_endpoint.hpp
test/CMakeLists.txt

mosquitto websocket requires "Sec-WebScoket-Protocol" : "mqtt".

Fixed #609.

---

include/mqtt/broker/broker.hpp

Fixed invalidated iterator use.

Fixed #749.

---

include/mqtt/endpoint.hpp
include/mqtt/shared_subscriptions.hpp
test/unit/CMakeLists.txt
test/unit/ut_shared_subscriptions.cpp

Added topic filter stating with $share creator from share_name and topic_filter.

Added shared_subscriptions error check.

---

include/mqtt/control_packet_type.hpp
include/mqtt/endpoint.hpp

Individual checking only, so far.

Added protocol error checking code.

---

include/mqtt/broker/broker.hpp
include/mqtt/endpoint.hpp
include/mqtt/exception.hpp

bad_message is mapped to malformed_packet.

Refined error codes.

---

include/mqtt/buffer.hpp
test/unit/CMakeLists.txt
test/unit/ut_buffer.cpp

Added lifetime query function for buffer.

---

test/unit/ut_value_allocator.cpp

Added test cases to improve coverage.

Fixed invalid test comment.

---

include/mqtt/constant.hpp

Fixed constexpr declaration

---

include/mqtt/log.hpp
include/mqtt/setup_log.hpp

Moved filtering point from sink to core.

Replaced global logger with thread_local one.

---

include/mqtt/client.hpp

It helps simple redirection on the same protocol.

Added host and port setter function.

---

include/mqtt/endpoint.hpp
include/mqtt/v5_message.hpp
test/system/st_topic_alias.cpp

Fixed moved from object accessing in add_prop().

Added topic alias automatically usingg functionality.

---

include/mqtt/async_client.hpp
include/mqtt/broker/broker.hpp
include/mqtt/constant.hpp
include/mqtt/endpoint.hpp
include/mqtt/property_variant.hpp
test/system/CMakeLists.txt
test/system/st_connect.cpp
test/system/st_maximum_packet_size.cpp

Refined CONNECT/CONNACK property setup logic.

Implemented maximum_packet_size.

---

include/mqtt/endpoint.hpp
include/mqtt/exception.hpp
test/system/st_maximum_packet_size.cpp

It is consistent to async APIs.

Added packet_size_error exception.

---

include/mqtt/endpoint.hpp

This check is done by do_async_publish.

Removed message_size error call.

---

include/mqtt/control_packet_type.hpp
include/mqtt/protocol_version.hpp
test/unit/CMakeLists.txt
test/unit/ut_code.cpp

Added missing unsbuscribe/unsuback control packet type string.
Unified undefined_* (added underscore).

Added test for codes.

---

test/system/st_connect.cpp

Fixed test precondition to increase coverage.

Removed unused handler.

---

include/mqtt/broker/broker.hpp
include/mqtt/broker/session_state.hpp
include/mqtt/constant.hpp
include/mqtt/endpoint.hpp
include/mqtt/tcp_endpoint.hpp
include/mqtt/type_erased_socket.hpp
include/mqtt/ws_endpoint.hpp

Fixed #856.

---

include/mqtt/endpoint.hpp
test/system/st_connect.cpp

async_force_disconnect handler is called when all shutdown process is finished.

Fixed async_force_disconnect.

---

include/mqtt/endpoint.hpp
include/mqtt/property.hpp
test/system/st_pubsub_1.cpp
test/unit/ut_property.cpp

Updated the type of correlation_data property body from string to binary.

Fixed #888.

---

example/no_tls_both.cpp
example/no_tls_server.cpp
example/no_tls_ws_both.cpp
example/no_tls_ws_server.cpp
example/tls_both.cpp
example/tls_server.cpp
example/tls_ws_both.cpp
example/tls_ws_server.cpp
example/v5_no_tls_both.cpp
example/v5_no_tls_server.cpp

When unsubscribing, not only topic_filter but also connection are compared.

Fixed #912.

---

include/mqtt/endpoint.hpp

Set client_id for server side (broker side) endpoint.

Fixed #916.

---

include/mqtt/async_client.hpp
include/mqtt/client.hpp
include/mqtt/property_variant.hpp
include/mqtt/sync_client.hpp

It can avoid redundant instantiation so compile speed up.

Made inline functions template.

---

include/mqtt/broker/subscription_map.hpp
include/mqtt/broker/topic_filter.hpp
include/mqtt/client.hpp

Added underlying layers (TCP, TLS, WS) connecting skipping functionality.

Implemented #969.

---

include/mqtt/server.hpp

Added client cert username queue.

Fixed client cert verify setting timing.
